name: e_commerce_school_project
description: "e_commerce with authentication , multi language , responsive
  design , firebase , payment gateway "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.17.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/core/assets/images/
    - lib/core/assets/icons/

  fonts:
    - family: Coco-Sharp
      fonts:
        - asset: lib/core/assets/fonts/Coco-Sharp-Regular-trial.ttf
