name: e_commerece_school_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  
  bloc: ^8.1.4
  flutter:
    sdk: flutter
    
  #state management
  flutter_bloc: ^8.1.5
  #adapting screen and font size.  
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
   


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - lib/core/assets/images/


