// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChaMqDXm0Ocg2NJnwG186ncHwMTnagtAw',
    appId: '1:969094576773:web:35795115f7969d4322c7ec',
    messagingSenderId: '969094576773',
    projectId: 'e-commmerce-ed90b',
    authDomain: 'e-commmerce-ed90b.firebaseapp.com',
    storageBucket: 'e-commmerce-ed90b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGlnc8b6Qt5wbVJCTNmZkRVY5DO43Zc0',
    appId: '1:969094576773:android:102be42a8546261c22c7ec',
    messagingSenderId: '969094576773',
    projectId: 'e-commmerce-ed90b',
    storageBucket: 'e-commmerce-ed90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhC55zNCxnLebaIYj-URvg3Spf4BnvRHo',
    appId: '1:969094576773:ios:6a71e2f547b26f8222c7ec',
    messagingSenderId: '969094576773',
    projectId: 'e-commmerce-ed90b',
    storageBucket: 'e-commmerce-ed90b.appspot.com',
    iosBundleId: 'com.example.eCommereceSchoolProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhC55zNCxnLebaIYj-URvg3Spf4BnvRHo',
    appId: '1:969094576773:ios:6a71e2f547b26f8222c7ec',
    messagingSenderId: '969094576773',
    projectId: 'e-commmerce-ed90b',
    storageBucket: 'e-commmerce-ed90b.appspot.com',
    iosBundleId: 'com.example.eCommereceSchoolProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChaMqDXm0Ocg2NJnwG186ncHwMTnagtAw',
    appId: '1:969094576773:web:35795115f7969d4322c7ec',
    messagingSenderId: '969094576773',
    projectId: 'e-commmerce-ed90b',
    authDomain: 'e-commmerce-ed90b.firebaseapp.com',
    storageBucket: 'e-commmerce-ed90b.appspot.com',
  );

}